#!/usr/bin/python3

import os

if not os.environ.get("PYFILE"):
    print('error, environment variable is not set')
    exit(11)

pyfile = os.environ["PYFILE"]

if not os.path.isfile(pyfile):
    print('error, python file not found')
    exit(1)
